import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import db from "../lib/supabase/db";
import ThemeProvider from "../lib/providers/next-theme-provider";
import { twMerge } from "tailwind-merge";
import AppStateProvider from "../lib/providers/state-provider";
import { SupabaseUserProvider } from "../lib/providers/supabase-user-provider";
import { Toaster } from "../components/ui/toaster";

console.log(db);

const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={twMerge(inter.className, "bg-background")}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <AppStateProvider>
            <SupabaseUserProvider>
              {children}
              <Toaster />
            </SupabaseUserProvider>
          </AppStateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
